//This file is autogenerated, do not edit

goog.require('pf.interface.Observable');
goog.require('pf.interface.Observer');
goog.require('evolution.states.module');
goog.require('evolution.states.firstController');
