//This file is autogenerated, do not edit

goog.require('pf.interface.Observable');
goog.require('pf.interface.Observer');
goog.require('pf.Clock.module');
goog.require('pf.Clock.clockDirective');
goog.require('pf.Clock');
goog.require('evolution.states.module');
goog.require('evolution.states.firstController');
